# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName(_fromUtf8("MainWindow"))
		MainWindow.resize(812, 506)
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
		self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setSpacing(0)
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.lcdNumberDROPosX1 = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX1.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX1.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX1.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX1.setNumDigits(6)
		self.lcdNumberDROPosX1.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX1.setObjectName(_fromUtf8("lcdNumberDROPosX1"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX1, 1, 0, 1, 1)
		self.lcdNumberDROPosC = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosC.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosC.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosC.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosC.setNumDigits(6)
		self.lcdNumberDROPosC.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosC.setObjectName(_fromUtf8("lcdNumberDROPosC"))
		self.gridLayout.addWidget(self.lcdNumberDROPosC, 1, 4, 1, 1)
		self.lcdNumberDROPosZ = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosZ.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosZ.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosZ.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosZ.setNumDigits(6)
		self.lcdNumberDROPosZ.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosZ.setObjectName(_fromUtf8("lcdNumberDROPosZ"))
		self.gridLayout.addWidget(self.lcdNumberDROPosZ, 1, 3, 1, 1)
		self.lcdNumberDROPosY = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosY.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosY.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosY.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosY.setNumDigits(6)
		self.lcdNumberDROPosY.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosY.setObjectName(_fromUtf8("lcdNumberDROPosY"))
		self.gridLayout.addWidget(self.lcdNumberDROPosY, 1, 2, 1, 1)
		self.lcdNumberDROPosX2 = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX2.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX2.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX2.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX2.setNumDigits(6)
		self.lcdNumberDROPosX2.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX2.setObjectName(_fromUtf8("lcdNumberDROPosX2"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX2, 1, 1, 1, 1)
		self.label = QtGui.QLabel(self.centralwidget)
		self.label.setObjectName(_fromUtf8("label"))
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.label_2 = QtGui.QLabel(self.centralwidget)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
		self.label_3 = QtGui.QLabel(self.centralwidget)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
		self.label_4 = QtGui.QLabel(self.centralwidget)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
		self.label_5 = QtGui.QLabel(self.centralwidget)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
		self.pushButtonNotStop = QtGui.QPushButton(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonNotStop.sizePolicy().hasHeightForWidth())
		self.pushButtonNotStop.setSizePolicy(sizePolicy)
		self.pushButtonNotStop.setObjectName(_fromUtf8("pushButtonNotStop"))
		self.gridLayout.addWidget(self.pushButtonNotStop, 0, 5, 3, 1)
		self.lcdNumberDROPosX = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX.setNumDigits(6)
		self.lcdNumberDROPosX.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX.setObjectName(_fromUtf8("lcdNumberDROPosX"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX, 2, 1, 1, 1)
		self.label_6 = QtGui.QLabel(self.centralwidget)
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
		self.verticalLayout_2.addLayout(self.gridLayout)
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
		self.gridLayout_3.setMargin(0)
		self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
		self.pushButtonMotorZAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorZAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorZAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorZAus.setCheckable(True)
		self.pushButtonMotorZAus.setChecked(False)
		self.pushButtonMotorZAus.setDefault(False)
		self.pushButtonMotorZAus.setObjectName(_fromUtf8("pushButtonMotorZAus"))
		self.gridLayout_3.addWidget(self.pushButtonMotorZAus, 4, 7, 1, 1)
		self.pushButtonInitX2 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitX2.sizePolicy().hasHeightForWidth())
		self.pushButtonInitX2.setSizePolicy(sizePolicy)
		self.pushButtonInitX2.setCheckable(False)
		self.pushButtonInitX2.setObjectName(_fromUtf8("pushButtonInitX2"))
		self.gridLayout_3.addWidget(self.pushButtonInitX2, 0, 5, 1, 1)
		self.pushButtonHomeX2 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeX2.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeX2.setSizePolicy(sizePolicy)
		self.pushButtonHomeX2.setCheckable(False)
		self.pushButtonHomeX2.setObjectName(_fromUtf8("pushButtonHomeX2"))
		self.gridLayout_3.addWidget(self.pushButtonHomeX2, 2, 5, 1, 1)
		self.pushButtonHomeZ = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeZ.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeZ.setSizePolicy(sizePolicy)
		self.pushButtonHomeZ.setCheckable(False)
		self.pushButtonHomeZ.setObjectName(_fromUtf8("pushButtonHomeZ"))
		self.gridLayout_3.addWidget(self.pushButtonHomeZ, 2, 7, 1, 1)
		self.pushButtonInitX = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitX.sizePolicy().hasHeightForWidth())
		self.pushButtonInitX.setSizePolicy(sizePolicy)
		self.pushButtonInitX.setCheckable(False)
		self.pushButtonInitX.setObjectName(_fromUtf8("pushButtonInitX"))
		self.gridLayout_3.addWidget(self.pushButtonInitX, 0, 4, 1, 1)
		self.pushButtonInitZ = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitZ.sizePolicy().hasHeightForWidth())
		self.pushButtonInitZ.setSizePolicy(sizePolicy)
		self.pushButtonInitZ.setCheckable(False)
		self.pushButtonInitZ.setObjectName(_fromUtf8("pushButtonInitZ"))
		self.gridLayout_3.addWidget(self.pushButtonInitZ, 0, 7, 1, 1)
		self.pushButtonInitY = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitY.sizePolicy().hasHeightForWidth())
		self.pushButtonInitY.setSizePolicy(sizePolicy)
		self.pushButtonInitY.setCheckable(False)
		self.pushButtonInitY.setObjectName(_fromUtf8("pushButtonInitY"))
		self.gridLayout_3.addWidget(self.pushButtonInitY, 0, 6, 1, 1)
		self.pushButtonHomeX = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeX.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeX.setSizePolicy(sizePolicy)
		self.pushButtonHomeX.setCheckable(False)
		self.pushButtonHomeX.setObjectName(_fromUtf8("pushButtonHomeX"))
		self.gridLayout_3.addWidget(self.pushButtonHomeX, 2, 4, 1, 1)
		self.pushButtonHomeY = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeY.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeY.setSizePolicy(sizePolicy)
		self.pushButtonHomeY.setCheckable(False)
		self.pushButtonHomeY.setObjectName(_fromUtf8("pushButtonHomeY"))
		self.gridLayout_3.addWidget(self.pushButtonHomeY, 2, 6, 1, 1)
		self.pushButtonMotorXAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorXAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorXAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorXAus.setCheckable(True)
		self.pushButtonMotorXAus.setChecked(False)
		self.pushButtonMotorXAus.setDefault(False)
		self.pushButtonMotorXAus.setObjectName(_fromUtf8("pushButtonMotorXAus"))
		self.gridLayout_3.addWidget(self.pushButtonMotorXAus, 4, 4, 1, 1)
		self.pushButtonMotorYAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorYAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorYAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorYAus.setCheckable(True)
		self.pushButtonMotorYAus.setChecked(False)
		self.pushButtonMotorYAus.setDefault(False)
		self.pushButtonMotorYAus.setObjectName(_fromUtf8("pushButtonMotorYAus"))
		self.gridLayout_3.addWidget(self.pushButtonMotorYAus, 4, 6, 1, 1)
		self.pushButtonInitC = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitC.sizePolicy().hasHeightForWidth())
		self.pushButtonInitC.setSizePolicy(sizePolicy)
		self.pushButtonInitC.setCheckable(False)
		self.pushButtonInitC.setObjectName(_fromUtf8("pushButtonInitC"))
		self.gridLayout_3.addWidget(self.pushButtonInitC, 0, 8, 1, 1)
		self.pushButtonHomeC = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeC.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeC.setSizePolicy(sizePolicy)
		self.pushButtonHomeC.setCheckable(False)
		self.pushButtonHomeC.setObjectName(_fromUtf8("pushButtonHomeC"))
		self.gridLayout_3.addWidget(self.pushButtonHomeC, 2, 8, 1, 1)
		self.pushButtonMotorCAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorCAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorCAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorCAus.setCheckable(True)
		self.pushButtonMotorCAus.setChecked(False)
		self.pushButtonMotorCAus.setDefault(False)
		self.pushButtonMotorCAus.setObjectName(_fromUtf8("pushButtonMotorCAus"))
		self.gridLayout_3.addWidget(self.pushButtonMotorCAus, 4, 8, 1, 1)
		self.pushButtonMotorX2Aus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorX2Aus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorX2Aus.setSizePolicy(sizePolicy)
		self.pushButtonMotorX2Aus.setCheckable(True)
		self.pushButtonMotorX2Aus.setChecked(False)
		self.pushButtonMotorX2Aus.setDefault(False)
		self.pushButtonMotorX2Aus.setObjectName(_fromUtf8("pushButtonMotorX2Aus"))
		self.gridLayout_3.addWidget(self.pushButtonMotorX2Aus, 4, 5, 1, 1)
		self.pushButtonJoysticMode = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonJoysticMode.sizePolicy().hasHeightForWidth())
		self.pushButtonJoysticMode.setSizePolicy(sizePolicy)
		self.pushButtonJoysticMode.setCheckable(True)
		self.pushButtonJoysticMode.setChecked(False)
		self.pushButtonJoysticMode.setDefault(False)
		self.pushButtonJoysticMode.setObjectName(_fromUtf8("pushButtonJoysticMode"))
		self.gridLayout_3.addWidget(self.pushButtonJoysticMode, 0, 3, 1, 1)
		self.pushButtonGoX0Y0 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoX0Y0.sizePolicy().hasHeightForWidth())
		self.pushButtonGoX0Y0.setSizePolicy(sizePolicy)
		self.pushButtonGoX0Y0.setCheckable(False)
		self.pushButtonGoX0Y0.setObjectName(_fromUtf8("pushButtonGoX0Y0"))
		self.gridLayout_3.addWidget(self.pushButtonGoX0Y0, 2, 1, 1, 1)
		self.pushButtonReadPos = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonReadPos.sizePolicy().hasHeightForWidth())
		self.pushButtonReadPos.setSizePolicy(sizePolicy)
		self.pushButtonReadPos.setCheckable(True)
		self.pushButtonReadPos.setChecked(True)
		self.pushButtonReadPos.setDefault(False)
		self.pushButtonReadPos.setObjectName(_fromUtf8("pushButtonReadPos"))
		self.gridLayout_3.addWidget(self.pushButtonReadPos, 0, 1, 1, 1)
		self.pushButtonGoX20 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoX20.sizePolicy().hasHeightForWidth())
		self.pushButtonGoX20.setSizePolicy(sizePolicy)
		self.pushButtonGoX20.setCheckable(False)
		self.pushButtonGoX20.setObjectName(_fromUtf8("pushButtonGoX20"))
		self.gridLayout_3.addWidget(self.pushButtonGoX20, 4, 1, 1, 1)
		self.pushButtonGoZmax = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoZmax.sizePolicy().hasHeightForWidth())
		self.pushButtonGoZmax.setSizePolicy(sizePolicy)
		self.pushButtonGoZmax.setCheckable(False)
		self.pushButtonGoZmax.setObjectName(_fromUtf8("pushButtonGoZmax"))
		self.gridLayout_3.addWidget(self.pushButtonGoZmax, 2, 3, 1, 1)
		self.pushButtonGoC0 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoC0.sizePolicy().hasHeightForWidth())
		self.pushButtonGoC0.setSizePolicy(sizePolicy)
		self.pushButtonGoC0.setCheckable(False)
		self.pushButtonGoC0.setObjectName(_fromUtf8("pushButtonGoC0"))
		self.gridLayout_3.addWidget(self.pushButtonGoC0, 4, 3, 1, 1)
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.verticalLayout_2.addWidget(self.tabWidget)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 25))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName(_fromUtf8("menuFile"))
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		MainWindow.setStatusBar(self.statusbar)
		self.actionExit = QtGui.QAction(MainWindow)
		self.actionExit.setObjectName(_fromUtf8("actionExit"))
		self.actionAbout = QtGui.QAction(MainWindow)
		self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
		self.actionHelp = QtGui.QAction(MainWindow)
		self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
		self.menuFile.addAction(self.actionExit)
		self.menuHelp.addAction(self.actionAbout)
		self.menuHelp.addAction(self.actionHelp)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		MainWindow.setTabOrder(self.tabWidget, self.pushButtonInitX)
		MainWindow.setTabOrder(self.pushButtonInitX, self.pushButtonInitY)
		MainWindow.setTabOrder(self.pushButtonInitY, self.pushButtonInitZ)
		MainWindow.setTabOrder(self.pushButtonInitZ, self.pushButtonHomeX)
		MainWindow.setTabOrder(self.pushButtonHomeX, self.pushButtonHomeY)
		MainWindow.setTabOrder(self.pushButtonHomeY, self.pushButtonHomeZ)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(_translate("MainWindow", "Python Qt servo mover", None))
		self.label.setText(_translate("MainWindow", "X1", None))
		self.label_2.setText(_translate("MainWindow", "X2", None))
		self.label_3.setText(_translate("MainWindow", "Y", None))
		self.label_4.setText(_translate("MainWindow", "Z", None))
		self.label_5.setText(_translate("MainWindow", "C", None))
		self.pushButtonNotStop.setText(_translate("MainWindow", "Not Stop", None))
		self.label_6.setText(_translate("MainWindow", "X", None))
		self.pushButtonMotorZAus.setText(_translate("MainWindow", "Motor Z an", None))
		self.pushButtonInitX2.setText(_translate("MainWindow", "Init X2 Regler", None))
		self.pushButtonHomeX2.setText(_translate("MainWindow", "Home X2", None))
		self.pushButtonHomeZ.setText(_translate("MainWindow", "Home Z", None))
		self.pushButtonInitX.setText(_translate("MainWindow", "Init X Regler", None))
		self.pushButtonInitZ.setText(_translate("MainWindow", "Init Z Regler", None))
		self.pushButtonInitY.setText(_translate("MainWindow", "Init Y Regler", None))
		self.pushButtonHomeX.setText(_translate("MainWindow", "Home X", None))
		self.pushButtonHomeY.setText(_translate("MainWindow", "Home Y", None))
		self.pushButtonMotorXAus.setText(_translate("MainWindow", "Motor X an", None))
		self.pushButtonMotorYAus.setText(_translate("MainWindow", "Motor Y an", None))
		self.pushButtonInitC.setText(_translate("MainWindow", "Init C Regler", None))
		self.pushButtonHomeC.setText(_translate("MainWindow", "Home C", None))
		self.pushButtonMotorCAus.setText(_translate("MainWindow", "Motor C an", None))
		self.pushButtonMotorX2Aus.setText(_translate("MainWindow", "Motor X2 an", None))
		self.pushButtonJoysticMode.setText(_translate("MainWindow", "Joystic mode", None))
		self.pushButtonGoX0Y0.setText(_translate("MainWindow", "Go X0 Y0", None))
		self.pushButtonReadPos.setText(_translate("MainWindow", "Read Positions", None))
		self.pushButtonGoX20.setText(_translate("MainWindow", "Go X2 0 ", None))
		self.pushButtonGoZmax.setText(_translate("MainWindow", "Go Z max", None))
		self.pushButtonGoC0.setText(_translate("MainWindow", "Go C 0 ", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
		self.menuFile.setTitle(_translate("MainWindow", "File", None))
		self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
		self.actionExit.setText(_translate("MainWindow", "Exit", None))
		self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
		self.actionAbout.setText(_translate("MainWindow", "About", None))
		self.actionHelp.setText(_translate("MainWindow", "Help", None))
		self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))


if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	MainWindow = QtGui.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

