# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName(_fromUtf8("MainWindow"))
		MainWindow.resize(768, 575)
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
		self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setSpacing(0)
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.lcdNumberDROPosC = QtGui.QLCDNumber(self.centralwidget)
		self.lcdNumberDROPosC.setEnabled(True)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosC.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosC.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosC.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosC.setNumDigits(6)
		self.lcdNumberDROPosC.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosC.setObjectName(_fromUtf8("lcdNumberDROPosC"))
		self.gridLayout.addWidget(self.lcdNumberDROPosC, 1, 4, 1, 1)
		self.lcdNumberDROPosZ = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosZ.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosZ.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosZ.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosZ.setNumDigits(6)
		self.lcdNumberDROPosZ.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosZ.setObjectName(_fromUtf8("lcdNumberDROPosZ"))
		self.gridLayout.addWidget(self.lcdNumberDROPosZ, 1, 3, 1, 1)
		self.lcdNumberDROPosY = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosY.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosY.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosY.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosY.setNumDigits(6)
		self.lcdNumberDROPosY.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosY.setObjectName(_fromUtf8("lcdNumberDROPosY"))
		self.gridLayout.addWidget(self.lcdNumberDROPosY, 1, 2, 1, 1)
		self.lcdNumberDROPosX2 = QtGui.QLCDNumber(self.centralwidget)
		self.lcdNumberDROPosX2.setEnabled(True)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX2.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX2.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX2.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX2.setNumDigits(6)
		self.lcdNumberDROPosX2.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX2.setObjectName(_fromUtf8("lcdNumberDROPosX2"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX2, 1, 1, 1, 1)
		self.label_2 = QtGui.QLabel(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
		self.label_2.setSizePolicy(sizePolicy)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
		self.label_3 = QtGui.QLabel(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
		self.label_3.setSizePolicy(sizePolicy)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
		self.label_4 = QtGui.QLabel(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
		self.label_4.setSizePolicy(sizePolicy)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
		self.label_5 = QtGui.QLabel(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
		self.label_5.setSizePolicy(sizePolicy)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
		self.pushButtonNotStop = QtGui.QPushButton(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonNotStop.sizePolicy().hasHeightForWidth())
		self.pushButtonNotStop.setSizePolicy(sizePolicy)
		self.pushButtonNotStop.setObjectName(_fromUtf8("pushButtonNotStop"))
		self.gridLayout.addWidget(self.pushButtonNotStop, 0, 5, 3, 1)
		self.lcdNumberDROPosX = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX.setNumDigits(6)
		self.lcdNumberDROPosX.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX.setObjectName(_fromUtf8("lcdNumberDROPosX"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX, 1, 0, 1, 1)
		self.label_6 = QtGui.QLabel(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
		self.label_6.setSizePolicy(sizePolicy)
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
		self.lcdNumberDROPosCf = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosCf.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosCf.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosCf.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosCf.setNumDigits(6)
		self.lcdNumberDROPosCf.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosCf.setObjectName(_fromUtf8("lcdNumberDROPosCf"))
		self.gridLayout.addWidget(self.lcdNumberDROPosCf, 2, 0, 1, 1)
		self.lcdNumberDROPosYf = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosYf.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosYf.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosYf.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosYf.setNumDigits(6)
		self.lcdNumberDROPosYf.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosYf.setObjectName(_fromUtf8("lcdNumberDROPosYf"))
		self.gridLayout.addWidget(self.lcdNumberDROPosYf, 2, 1, 1, 1)
		self.lcdNumberDROPosX2f = QtGui.QLCDNumber(self.centralwidget)
		self.lcdNumberDROPosX2f.setEnabled(True)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosX2f.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosX2f.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosX2f.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosX2f.setNumDigits(6)
		self.lcdNumberDROPosX2f.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosX2f.setObjectName(_fromUtf8("lcdNumberDROPosX2f"))
		self.gridLayout.addWidget(self.lcdNumberDROPosX2f, 2, 3, 1, 1)
		self.lcdNumberDROPosXf = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosXf.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosXf.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosXf.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosXf.setNumDigits(6)
		self.lcdNumberDROPosXf.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosXf.setObjectName(_fromUtf8("lcdNumberDROPosXf"))
		self.gridLayout.addWidget(self.lcdNumberDROPosXf, 2, 4, 1, 1)
		self.lcdNumberDROPosZf = QtGui.QLCDNumber(self.centralwidget)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lcdNumberDROPosZf.sizePolicy().hasHeightForWidth())
		self.lcdNumberDROPosZf.setSizePolicy(sizePolicy)
		self.lcdNumberDROPosZf.setMinimumSize(QtCore.QSize(0, 46))
		self.lcdNumberDROPosZf.setNumDigits(6)
		self.lcdNumberDROPosZf.setSegmentStyle(QtGui.QLCDNumber.Filled)
		self.lcdNumberDROPosZf.setObjectName(_fromUtf8("lcdNumberDROPosZf"))
		self.gridLayout.addWidget(self.lcdNumberDROPosZf, 2, 2, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
		self.gridLayout_7.setMargin(0)
		self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
		self.pushButtonReadPos = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonReadPos.sizePolicy().hasHeightForWidth())
		self.pushButtonReadPos.setSizePolicy(sizePolicy)
		self.pushButtonReadPos.setCheckable(True)
		self.pushButtonReadPos.setChecked(True)
		self.pushButtonReadPos.setDefault(False)
		self.pushButtonReadPos.setObjectName(_fromUtf8("pushButtonReadPos"))
		self.gridLayout_7.addWidget(self.pushButtonReadPos, 0, 0, 1, 1)
		self.pushButtonHomeAll = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeAll.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeAll.setSizePolicy(sizePolicy)
		self.pushButtonHomeAll.setCheckable(False)
		self.pushButtonHomeAll.setChecked(False)
		self.pushButtonHomeAll.setDefault(False)
		self.pushButtonHomeAll.setObjectName(_fromUtf8("pushButtonHomeAll"))
		self.gridLayout_7.addWidget(self.pushButtonHomeAll, 0, 1, 1, 1)
		self.pushButtonInitX = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitX.sizePolicy().hasHeightForWidth())
		self.pushButtonInitX.setSizePolicy(sizePolicy)
		self.pushButtonInitX.setCheckable(False)
		self.pushButtonInitX.setObjectName(_fromUtf8("pushButtonInitX"))
		self.gridLayout_7.addWidget(self.pushButtonInitX, 0, 2, 1, 1)
		self.pushButtonInitX2 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitX2.sizePolicy().hasHeightForWidth())
		self.pushButtonInitX2.setSizePolicy(sizePolicy)
		self.pushButtonInitX2.setCheckable(False)
		self.pushButtonInitX2.setObjectName(_fromUtf8("pushButtonInitX2"))
		self.gridLayout_7.addWidget(self.pushButtonInitX2, 0, 3, 1, 1)
		self.pushButtonInitY = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitY.sizePolicy().hasHeightForWidth())
		self.pushButtonInitY.setSizePolicy(sizePolicy)
		self.pushButtonInitY.setCheckable(False)
		self.pushButtonInitY.setObjectName(_fromUtf8("pushButtonInitY"))
		self.gridLayout_7.addWidget(self.pushButtonInitY, 0, 4, 1, 1)
		self.pushButtonInitZ = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitZ.sizePolicy().hasHeightForWidth())
		self.pushButtonInitZ.setSizePolicy(sizePolicy)
		self.pushButtonInitZ.setCheckable(False)
		self.pushButtonInitZ.setObjectName(_fromUtf8("pushButtonInitZ"))
		self.gridLayout_7.addWidget(self.pushButtonInitZ, 0, 5, 1, 1)
		self.pushButtonInitC = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonInitC.sizePolicy().hasHeightForWidth())
		self.pushButtonInitC.setSizePolicy(sizePolicy)
		self.pushButtonInitC.setCheckable(False)
		self.pushButtonInitC.setObjectName(_fromUtf8("pushButtonInitC"))
		self.gridLayout_7.addWidget(self.pushButtonInitC, 0, 6, 1, 1)
		self.pushButtonGoX0Y0 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoX0Y0.sizePolicy().hasHeightForWidth())
		self.pushButtonGoX0Y0.setSizePolicy(sizePolicy)
		self.pushButtonGoX0Y0.setCheckable(False)
		self.pushButtonGoX0Y0.setObjectName(_fromUtf8("pushButtonGoX0Y0"))
		self.gridLayout_7.addWidget(self.pushButtonGoX0Y0, 1, 0, 1, 1)
		self.pushButtonGoZmax = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoZmax.sizePolicy().hasHeightForWidth())
		self.pushButtonGoZmax.setSizePolicy(sizePolicy)
		self.pushButtonGoZmax.setCheckable(False)
		self.pushButtonGoZmax.setObjectName(_fromUtf8("pushButtonGoZmax"))
		self.gridLayout_7.addWidget(self.pushButtonGoZmax, 1, 1, 1, 1)
		self.pushButtonHomeX = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeX.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeX.setSizePolicy(sizePolicy)
		self.pushButtonHomeX.setCheckable(True)
		self.pushButtonHomeX.setObjectName(_fromUtf8("pushButtonHomeX"))
		self.gridLayout_7.addWidget(self.pushButtonHomeX, 1, 2, 1, 1)
		self.pushButtonHomeX2 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeX2.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeX2.setSizePolicy(sizePolicy)
		self.pushButtonHomeX2.setCheckable(True)
		self.pushButtonHomeX2.setObjectName(_fromUtf8("pushButtonHomeX2"))
		self.gridLayout_7.addWidget(self.pushButtonHomeX2, 1, 3, 1, 1)
		self.pushButtonHomeY = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeY.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeY.setSizePolicy(sizePolicy)
		self.pushButtonHomeY.setCheckable(True)
		self.pushButtonHomeY.setObjectName(_fromUtf8("pushButtonHomeY"))
		self.gridLayout_7.addWidget(self.pushButtonHomeY, 1, 4, 1, 1)
		self.pushButtonHomeZ = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeZ.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeZ.setSizePolicy(sizePolicy)
		self.pushButtonHomeZ.setCheckable(True)
		self.pushButtonHomeZ.setObjectName(_fromUtf8("pushButtonHomeZ"))
		self.gridLayout_7.addWidget(self.pushButtonHomeZ, 1, 5, 1, 1)
		self.pushButtonHomeC = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonHomeC.sizePolicy().hasHeightForWidth())
		self.pushButtonHomeC.setSizePolicy(sizePolicy)
		self.pushButtonHomeC.setCheckable(True)
		self.pushButtonHomeC.setObjectName(_fromUtf8("pushButtonHomeC"))
		self.gridLayout_7.addWidget(self.pushButtonHomeC, 1, 6, 1, 1)
		self.pushButtonGoX20 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoX20.sizePolicy().hasHeightForWidth())
		self.pushButtonGoX20.setSizePolicy(sizePolicy)
		self.pushButtonGoX20.setCheckable(False)
		self.pushButtonGoX20.setObjectName(_fromUtf8("pushButtonGoX20"))
		self.gridLayout_7.addWidget(self.pushButtonGoX20, 2, 0, 1, 1)
		self.pushButtonGoC0 = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGoC0.sizePolicy().hasHeightForWidth())
		self.pushButtonGoC0.setSizePolicy(sizePolicy)
		self.pushButtonGoC0.setCheckable(False)
		self.pushButtonGoC0.setObjectName(_fromUtf8("pushButtonGoC0"))
		self.gridLayout_7.addWidget(self.pushButtonGoC0, 2, 1, 1, 1)
		self.pushButtonMotorXAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorXAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorXAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorXAus.setCheckable(True)
		self.pushButtonMotorXAus.setChecked(False)
		self.pushButtonMotorXAus.setDefault(False)
		self.pushButtonMotorXAus.setObjectName(_fromUtf8("pushButtonMotorXAus"))
		self.gridLayout_7.addWidget(self.pushButtonMotorXAus, 2, 2, 1, 1)
		self.pushButtonMotorX2Aus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorX2Aus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorX2Aus.setSizePolicy(sizePolicy)
		self.pushButtonMotorX2Aus.setCheckable(True)
		self.pushButtonMotorX2Aus.setChecked(False)
		self.pushButtonMotorX2Aus.setDefault(False)
		self.pushButtonMotorX2Aus.setObjectName(_fromUtf8("pushButtonMotorX2Aus"))
		self.gridLayout_7.addWidget(self.pushButtonMotorX2Aus, 2, 3, 1, 1)
		self.pushButtonMotorYAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorYAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorYAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorYAus.setCheckable(True)
		self.pushButtonMotorYAus.setChecked(False)
		self.pushButtonMotorYAus.setDefault(False)
		self.pushButtonMotorYAus.setObjectName(_fromUtf8("pushButtonMotorYAus"))
		self.gridLayout_7.addWidget(self.pushButtonMotorYAus, 2, 4, 1, 1)
		self.pushButtonMotorZAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorZAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorZAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorZAus.setCheckable(True)
		self.pushButtonMotorZAus.setChecked(False)
		self.pushButtonMotorZAus.setDefault(False)
		self.pushButtonMotorZAus.setObjectName(_fromUtf8("pushButtonMotorZAus"))
		self.gridLayout_7.addWidget(self.pushButtonMotorZAus, 2, 5, 1, 1)
		self.pushButtonMotorCAus = QtGui.QPushButton(self.tab_2)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonMotorCAus.sizePolicy().hasHeightForWidth())
		self.pushButtonMotorCAus.setSizePolicy(sizePolicy)
		self.pushButtonMotorCAus.setCheckable(True)
		self.pushButtonMotorCAus.setChecked(False)
		self.pushButtonMotorCAus.setDefault(False)
		self.pushButtonMotorCAus.setObjectName(_fromUtf8("pushButtonMotorCAus"))
		self.gridLayout_7.addWidget(self.pushButtonMotorCAus, 2, 6, 1, 1)
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.gridLayout_4 = QtGui.QGridLayout(self.tab)
		self.gridLayout_4.setMargin(0)
		self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
		self.label_12 = QtGui.QLabel(self.tab)
		self.label_12.setObjectName(_fromUtf8("label_12"))
		self.gridLayout_4.addWidget(self.label_12, 7, 0, 1, 2)
		self.label_7 = QtGui.QLabel(self.tab)
		self.label_7.setObjectName(_fromUtf8("label_7"))
		self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
		self.X1set = QtGui.QSlider(self.tab)
		self.X1set.setMinimum(-16000)
		self.X1set.setMaximum(16300)
		self.X1set.setPageStep(100)
		self.X1set.setOrientation(QtCore.Qt.Horizontal)
		self.X1set.setTickPosition(QtGui.QSlider.TicksAbove)
		self.X1set.setTickInterval(1000)
		self.X1set.setObjectName(_fromUtf8("X1set"))
		self.gridLayout_4.addWidget(self.X1set, 4, 3, 2, 1)
		self.Vmaxset = QtGui.QSlider(self.tab)
		self.Vmaxset.setMaximum(200000)
		self.Vmaxset.setPageStep(100)
		self.Vmaxset.setProperty("value", 20000)
		self.Vmaxset.setSliderPosition(20000)
		self.Vmaxset.setOrientation(QtCore.Qt.Horizontal)
		self.Vmaxset.setTickPosition(QtGui.QSlider.TicksAbove)
		self.Vmaxset.setTickInterval(1000)
		self.Vmaxset.setObjectName(_fromUtf8("Vmaxset"))
		self.gridLayout_4.addWidget(self.Vmaxset, 7, 3, 1, 1)
		self.label_10 = QtGui.QLabel(self.tab)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
		self.label_10.setSizePolicy(sizePolicy)
		self.label_10.setObjectName(_fromUtf8("label_10"))
		self.gridLayout_4.addWidget(self.label_10, 0, 4, 1, 1)
		self.spinBoxC = QtGui.QSpinBox(self.tab)
		self.spinBoxC.setMinimum(-4100)
		self.spinBoxC.setMaximum(4100)
		self.spinBoxC.setObjectName(_fromUtf8("spinBoxC"))
		self.gridLayout_4.addWidget(self.spinBoxC, 0, 2, 1, 1)
		self.Yset = QtGui.QSlider(self.tab)
		self.Yset.setMinimum(-19260)
		self.Yset.setMaximum(22080)
		self.Yset.setPageStep(100)
		self.Yset.setOrientation(QtCore.Qt.Vertical)
		self.Yset.setTickPosition(QtGui.QSlider.TicksBelow)
		self.Yset.setTickInterval(1000)
		self.Yset.setObjectName(_fromUtf8("Yset"))
		self.gridLayout_4.addWidget(self.Yset, 2, 4, 1, 1)
		self.spinBoxY = QtGui.QSpinBox(self.tab)
		self.spinBoxY.setMinimum(-19260)
		self.spinBoxY.setMaximum(22080)
		self.spinBoxY.setSingleStep(1)
		self.spinBoxY.setObjectName(_fromUtf8("spinBoxY"))
		self.gridLayout_4.addWidget(self.spinBoxY, 1, 4, 1, 1)
		self.Zset = QtGui.QSlider(self.tab)
		self.Zset.setMaximum(104000)
		self.Zset.setPageStep(100)
		self.Zset.setProperty("value", 100000)
		self.Zset.setOrientation(QtCore.Qt.Vertical)
		self.Zset.setTickPosition(QtGui.QSlider.TicksBelow)
		self.Zset.setTickInterval(10000)
		self.Zset.setObjectName(_fromUtf8("Zset"))
		self.gridLayout_4.addWidget(self.Zset, 2, 5, 1, 1)
		self.spinBoxX2 = QtGui.QSpinBox(self.tab)
		self.spinBoxX2.setMinimum(-4600)
		self.spinBoxX2.setMaximum(7500)
		self.spinBoxX2.setObjectName(_fromUtf8("spinBoxX2"))
		self.gridLayout_4.addWidget(self.spinBoxX2, 6, 1, 1, 2)
		self.spinBoxZ = QtGui.QSpinBox(self.tab)
		self.spinBoxZ.setMaximum(104000)
		self.spinBoxZ.setProperty("value", 100000)
		self.spinBoxZ.setObjectName(_fromUtf8("spinBoxZ"))
		self.gridLayout_4.addWidget(self.spinBoxZ, 1, 5, 1, 1)
		self.X2set = QtGui.QSlider(self.tab)
		self.X2set.setMinimum(-4600)
		self.X2set.setMaximum(7500)
		self.X2set.setPageStep(100)
		self.X2set.setOrientation(QtCore.Qt.Horizontal)
		self.X2set.setInvertedAppearance(True)
		self.X2set.setTickPosition(QtGui.QSlider.TicksAbove)
		self.X2set.setTickInterval(1000)
		self.X2set.setObjectName(_fromUtf8("X2set"))
		self.gridLayout_4.addWidget(self.X2set, 6, 3, 1, 1)
		self.pushButtonGo = QtGui.QPushButton(self.tab)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonGo.sizePolicy().hasHeightForWidth())
		self.pushButtonGo.setSizePolicy(sizePolicy)
		self.pushButtonGo.setObjectName(_fromUtf8("pushButtonGo"))
		self.gridLayout_4.addWidget(self.pushButtonGo, 3, 4, 5, 2)
		self.spinBoxVmax = QtGui.QSpinBox(self.tab)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.spinBoxVmax.sizePolicy().hasHeightForWidth())
		self.spinBoxVmax.setSizePolicy(sizePolicy)
		self.spinBoxVmax.setMaximum(200000)
		self.spinBoxVmax.setProperty("value", 20000)
		self.spinBoxVmax.setObjectName(_fromUtf8("spinBoxVmax"))
		self.gridLayout_4.addWidget(self.spinBoxVmax, 7, 2, 1, 1)
		self.label_8 = QtGui.QLabel(self.tab)
		self.label_8.setObjectName(_fromUtf8("label_8"))
		self.gridLayout_4.addWidget(self.label_8, 6, 0, 1, 1)
		self.label_9 = QtGui.QLabel(self.tab)
		self.label_9.setObjectName(_fromUtf8("label_9"))
		self.gridLayout_4.addWidget(self.label_9, 0, 0, 1, 1)
		self.label_11 = QtGui.QLabel(self.tab)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
		self.label_11.setSizePolicy(sizePolicy)
		self.label_11.setObjectName(_fromUtf8("label_11"))
		self.gridLayout_4.addWidget(self.label_11, 0, 5, 1, 1)
		self.Cset = QtGui.QDial(self.tab)
		self.Cset.setMinimum(-4100)
		self.Cset.setMaximum(4100)
		self.Cset.setPageStep(50)
		self.Cset.setSliderPosition(0)
		self.Cset.setInvertedAppearance(True)
		self.Cset.setWrapping(True)
		self.Cset.setNotchTarget(10.0)
		self.Cset.setNotchesVisible(True)
		self.Cset.setObjectName(_fromUtf8("Cset"))
		self.gridLayout_4.addWidget(self.Cset, 0, 3, 3, 1)
		self.spinBoxX = QtGui.QSpinBox(self.tab)
		self.spinBoxX.setMinimum(-16000)
		self.spinBoxX.setMaximum(16300)
		self.spinBoxX.setObjectName(_fromUtf8("spinBoxX"))
		self.gridLayout_4.addWidget(self.spinBoxX, 4, 1, 2, 2)
		self.tabWidget.addTab(self.tab, _fromUtf8(""))
		self.tab_3 = QtGui.QWidget()
		self.tab_3.setObjectName(_fromUtf8("tab_3"))
		self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
		self.gridLayout_5.setMargin(0)
		self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
		self.pushButtonToolTipVac = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonToolTipVac.sizePolicy().hasHeightForWidth())
		self.pushButtonToolTipVac.setSizePolicy(sizePolicy)
		self.pushButtonToolTipVac.setCheckable(True)
		self.pushButtonToolTipVac.setChecked(False)
		self.pushButtonToolTipVac.setDefault(False)
		self.pushButtonToolTipVac.setObjectName(_fromUtf8("pushButtonToolTipVac"))
		self.gridLayout_5.addWidget(self.pushButtonToolTipVac, 0, 4, 1, 1)
		self.label = QtGui.QLabel(self.tab_3)
		self.label.setObjectName(_fromUtf8("label"))
		self.gridLayout_5.addWidget(self.label, 3, 0, 1, 1)
		self.pushButtonUplight = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonUplight.sizePolicy().hasHeightForWidth())
		self.pushButtonUplight.setSizePolicy(sizePolicy)
		self.pushButtonUplight.setCheckable(True)
		self.pushButtonUplight.setChecked(False)
		self.pushButtonUplight.setDefault(False)
		self.pushButtonUplight.setObjectName(_fromUtf8("pushButtonUplight"))
		self.gridLayout_5.addWidget(self.pushButtonUplight, 0, 1, 1, 1)
		self.pushButtonToolTipVacRead = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonToolTipVacRead.sizePolicy().hasHeightForWidth())
		self.pushButtonToolTipVacRead.setSizePolicy(sizePolicy)
		self.pushButtonToolTipVacRead.setCheckable(False)
		self.pushButtonToolTipVacRead.setChecked(False)
		self.pushButtonToolTipVacRead.setAutoRepeat(True)
		self.pushButtonToolTipVacRead.setDefault(False)
		self.pushButtonToolTipVacRead.setObjectName(_fromUtf8("pushButtonToolTipVacRead"))
		self.gridLayout_5.addWidget(self.pushButtonToolTipVacRead, 0, 5, 1, 1)
		self.pushButtonDownlight = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonDownlight.sizePolicy().hasHeightForWidth())
		self.pushButtonDownlight.setSizePolicy(sizePolicy)
		self.pushButtonDownlight.setCheckable(True)
		self.pushButtonDownlight.setChecked(False)
		self.pushButtonDownlight.setDefault(False)
		self.pushButtonDownlight.setObjectName(_fromUtf8("pushButtonDownlight"))
		self.gridLayout_5.addWidget(self.pushButtonDownlight, 0, 2, 1, 1)
		self.pushButtonToolChangerVac = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(1)
		sizePolicy.setHeightForWidth(self.pushButtonToolChangerVac.sizePolicy().hasHeightForWidth())
		self.pushButtonToolChangerVac.setSizePolicy(sizePolicy)
		self.pushButtonToolChangerVac.setCheckable(True)
		self.pushButtonToolChangerVac.setChecked(True)
		self.pushButtonToolChangerVac.setDefault(False)
		self.pushButtonToolChangerVac.setObjectName(_fromUtf8("pushButtonToolChangerVac"))
		self.gridLayout_5.addWidget(self.pushButtonToolChangerVac, 0, 3, 1, 1)
		self.pushButtonPump = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonPump.sizePolicy().hasHeightForWidth())
		self.pushButtonPump.setSizePolicy(sizePolicy)
		self.pushButtonPump.setCheckable(True)
		self.pushButtonPump.setChecked(False)
		self.pushButtonPump.setDefault(False)
		self.pushButtonPump.setObjectName(_fromUtf8("pushButtonPump"))
		self.gridLayout_5.addWidget(self.pushButtonPump, 0, 0, 1, 1)
		self.label_13 = QtGui.QLabel(self.tab_3)
		self.label_13.setObjectName(_fromUtf8("label_13"))
		self.gridLayout_5.addWidget(self.label_13, 1, 0, 1, 1)
		self.pushButtonTouchDownRead = QtGui.QPushButton(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonTouchDownRead.sizePolicy().hasHeightForWidth())
		self.pushButtonTouchDownRead.setSizePolicy(sizePolicy)
		self.pushButtonTouchDownRead.setCheckable(False)
		self.pushButtonTouchDownRead.setChecked(False)
		self.pushButtonTouchDownRead.setAutoRepeat(True)
		self.pushButtonTouchDownRead.setDefault(False)
		self.pushButtonTouchDownRead.setObjectName(_fromUtf8("pushButtonTouchDownRead"))
		self.gridLayout_5.addWidget(self.pushButtonTouchDownRead, 0, 6, 1, 1)
		self.progressBarToolTipVacRead = QtGui.QProgressBar(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progressBarToolTipVacRead.sizePolicy().hasHeightForWidth())
		self.progressBarToolTipVacRead.setSizePolicy(sizePolicy)
		self.progressBarToolTipVacRead.setMaximum(1000)
		self.progressBarToolTipVacRead.setProperty("value", 950)
		self.progressBarToolTipVacRead.setObjectName(_fromUtf8("progressBarToolTipVacRead"))
		self.gridLayout_5.addWidget(self.progressBarToolTipVacRead, 2, 0, 1, 7)
		self.progressBarTouchDownRead = QtGui.QProgressBar(self.tab_3)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.progressBarTouchDownRead.sizePolicy().hasHeightForWidth())
		self.progressBarTouchDownRead.setSizePolicy(sizePolicy)
		self.progressBarTouchDownRead.setMaximum(100)
		self.progressBarTouchDownRead.setProperty("value", 50)
		self.progressBarTouchDownRead.setObjectName(_fromUtf8("progressBarTouchDownRead"))
		self.gridLayout_5.addWidget(self.progressBarTouchDownRead, 4, 0, 1, 7)
		self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
		self.tab_5 = QtGui.QWidget()
		self.tab_5.setObjectName(_fromUtf8("tab_5"))
		self.gridLayout_3 = QtGui.QGridLayout(self.tab_5)
		self.gridLayout_3.setMargin(0)
		self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
		self.pushButton_ZM = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_ZM.sizePolicy().hasHeightForWidth())
		self.pushButton_ZM.setSizePolicy(sizePolicy)
		self.pushButton_ZM.setObjectName(_fromUtf8("pushButton_ZM"))
		self.gridLayout_3.addWidget(self.pushButton_ZM, 4, 6, 1, 1)
		self.pushButton_XM_2 = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_XM_2.sizePolicy().hasHeightForWidth())
		self.pushButton_XM_2.setSizePolicy(sizePolicy)
		self.pushButton_XM_2.setObjectName(_fromUtf8("pushButton_XM_2"))
		self.gridLayout_3.addWidget(self.pushButton_XM_2, 3, 3, 1, 2)
		self.pushButton_YM = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_YM.sizePolicy().hasHeightForWidth())
		self.pushButton_YM.setSizePolicy(sizePolicy)
		self.pushButton_YM.setObjectName(_fromUtf8("pushButton_YM"))
		self.gridLayout_3.addWidget(self.pushButton_YM, 4, 2, 1, 2)
		self.pushButton_YP = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_YP.sizePolicy().hasHeightForWidth())
		self.pushButton_YP.setSizePolicy(sizePolicy)
		self.pushButton_YP.setObjectName(_fromUtf8("pushButton_YP"))
		self.gridLayout_3.addWidget(self.pushButton_YP, 2, 2, 1, 2)
		self.pushButton_XM = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_XM.sizePolicy().hasHeightForWidth())
		self.pushButton_XM.setSizePolicy(sizePolicy)
		self.pushButton_XM.setObjectName(_fromUtf8("pushButton_XM"))
		self.gridLayout_3.addWidget(self.pushButton_XM, 3, 1, 1, 2)
		self.pushButton_ZP = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_ZP.sizePolicy().hasHeightForWidth())
		self.pushButton_ZP.setSizePolicy(sizePolicy)
		self.pushButton_ZP.setObjectName(_fromUtf8("pushButton_ZP"))
		self.gridLayout_3.addWidget(self.pushButton_ZP, 2, 6, 1, 1)
		self.pushButtonJoysticMode = QtGui.QPushButton(self.tab_5)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButtonJoysticMode.sizePolicy().hasHeightForWidth())
		self.pushButtonJoysticMode.setSizePolicy(sizePolicy)
		self.pushButtonJoysticMode.setCheckable(True)
		self.pushButtonJoysticMode.setObjectName(_fromUtf8("pushButtonJoysticMode"))
		self.gridLayout_3.addWidget(self.pushButtonJoysticMode, 2, 1, 1, 1)
		self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_5)
		self.doubleSpinBox.setDecimals(3)
		self.doubleSpinBox.setMinimum(0.001)
		self.doubleSpinBox.setMaximum(100.0)
		self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
		self.gridLayout_3.addWidget(self.doubleSpinBox, 2, 4, 1, 1)
		self.verticalSlider_StepsXY = QtGui.QSlider(self.tab_5)
		self.verticalSlider_StepsXY.setMinimum(1)
		self.verticalSlider_StepsXY.setMaximum(10)
		self.verticalSlider_StepsXY.setPageStep(10)
		self.verticalSlider_StepsXY.setOrientation(QtCore.Qt.Vertical)
		self.verticalSlider_StepsXY.setTickPosition(QtGui.QSlider.TicksAbove)
		self.verticalSlider_StepsXY.setTickInterval(1)
		self.verticalSlider_StepsXY.setObjectName(_fromUtf8("verticalSlider_StepsXY"))
		self.gridLayout_3.addWidget(self.verticalSlider_StepsXY, 2, 5, 3, 1)
		self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_5)
		self.doubleSpinBox_2.setDecimals(3)
		self.doubleSpinBox_2.setMinimum(0.001)
		self.doubleSpinBox_2.setMaximum(100.0)
		self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
		self.gridLayout_3.addWidget(self.doubleSpinBox_2, 3, 6, 1, 1)
		self.verticalSlider_StepsZ = QtGui.QSlider(self.tab_5)
		self.verticalSlider_StepsZ.setMinimum(1)
		self.verticalSlider_StepsZ.setMaximum(10)
		self.verticalSlider_StepsZ.setPageStep(10)
		self.verticalSlider_StepsZ.setOrientation(QtCore.Qt.Vertical)
		self.verticalSlider_StepsZ.setTickPosition(QtGui.QSlider.TicksAbove)
		self.verticalSlider_StepsZ.setTickInterval(1)
		self.verticalSlider_StepsZ.setObjectName(_fromUtf8("verticalSlider_StepsZ"))
		self.gridLayout_3.addWidget(self.verticalSlider_StepsZ, 2, 7, 3, 1)
		self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
		self.tab_6 = QtGui.QWidget()
		self.tab_6.setObjectName(_fromUtf8("tab_6"))
		self.gridLayout_6 = QtGui.QGridLayout(self.tab_6)
		self.gridLayout_6.setMargin(0)
		self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
		self.label_14 = QtGui.QLabel(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
		self.label_14.setSizePolicy(sizePolicy)
		self.label_14.setObjectName(_fromUtf8("label_14"))
		self.gridLayout_6.addWidget(self.label_14, 0, 1, 1, 1)
		self.label_15 = QtGui.QLabel(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
		self.label_15.setSizePolicy(sizePolicy)
		self.label_15.setObjectName(_fromUtf8("label_15"))
		self.gridLayout_6.addWidget(self.label_15, 0, 2, 1, 1)
		self.label_16 = QtGui.QLabel(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
		self.label_16.setSizePolicy(sizePolicy)
		self.label_16.setObjectName(_fromUtf8("label_16"))
		self.gridLayout_6.addWidget(self.label_16, 0, 3, 1, 1)
		self.label_22 = QtGui.QLabel(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
		self.label_22.setSizePolicy(sizePolicy)
		self.label_22.setObjectName(_fromUtf8("label_22"))
		self.gridLayout_6.addWidget(self.label_22, 0, 4, 1, 1)
		self.label_17 = QtGui.QLabel(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
		self.label_17.setSizePolicy(sizePolicy)
		self.label_17.setObjectName(_fromUtf8("label_17"))
		self.gridLayout_6.addWidget(self.label_17, 1, 0, 1, 1)
		self.doubleSpinBox_ParkX = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_ParkX.setDecimals(3)
		self.doubleSpinBox_ParkX.setMinimum(-200.0)
		self.doubleSpinBox_ParkX.setMaximum(200.0)
		self.doubleSpinBox_ParkX.setSingleStep(0.001)
		self.doubleSpinBox_ParkX.setObjectName(_fromUtf8("doubleSpinBox_ParkX"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_ParkX, 1, 1, 1, 1)
		self.doubleSpinBox_ParkY = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_ParkY.setDecimals(3)
		self.doubleSpinBox_ParkY.setMinimum(-200.0)
		self.doubleSpinBox_ParkY.setMaximum(200.0)
		self.doubleSpinBox_ParkY.setSingleStep(0.001)
		self.doubleSpinBox_ParkY.setObjectName(_fromUtf8("doubleSpinBox_ParkY"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_ParkY, 1, 2, 1, 1)
		self.doubleSpinBox_ParkZ = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_ParkZ.setDecimals(3)
		self.doubleSpinBox_ParkZ.setMinimum(-50.0)
		self.doubleSpinBox_ParkZ.setMaximum(4.0)
		self.doubleSpinBox_ParkZ.setSingleStep(0.001)
		self.doubleSpinBox_ParkZ.setObjectName(_fromUtf8("doubleSpinBox_ParkZ"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_ParkZ, 1, 3, 1, 1)
		self.doubleSpinBox_ParkSpeed = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_ParkSpeed.setDecimals(3)
		self.doubleSpinBox_ParkSpeed.setMinimum(-200.0)
		self.doubleSpinBox_ParkSpeed.setMaximum(200.0)
		self.doubleSpinBox_ParkSpeed.setSingleStep(0.001)
		self.doubleSpinBox_ParkSpeed.setObjectName(_fromUtf8("doubleSpinBox_ParkSpeed"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_ParkSpeed, 1, 4, 1, 1)
		self.pushButton_CapturePark = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_CapturePark.sizePolicy().hasHeightForWidth())
		self.pushButton_CapturePark.setSizePolicy(sizePolicy)
		self.pushButton_CapturePark.setObjectName(_fromUtf8("pushButton_CapturePark"))
		self.gridLayout_6.addWidget(self.pushButton_CapturePark, 1, 5, 1, 1)
		self.pushButton_GoPark = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_GoPark.sizePolicy().hasHeightForWidth())
		self.pushButton_GoPark.setSizePolicy(sizePolicy)
		self.pushButton_GoPark.setObjectName(_fromUtf8("pushButton_GoPark"))
		self.gridLayout_6.addWidget(self.pushButton_GoPark, 1, 6, 1, 1)
		self.label_18 = QtGui.QLabel(self.tab_6)
		self.label_18.setObjectName(_fromUtf8("label_18"))
		self.gridLayout_6.addWidget(self.label_18, 2, 0, 1, 1)
		self.doubleSpinBox_GrindX = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_GrindX.setDecimals(3)
		self.doubleSpinBox_GrindX.setMinimum(-200.0)
		self.doubleSpinBox_GrindX.setMaximum(200.0)
		self.doubleSpinBox_GrindX.setSingleStep(0.001)
		self.doubleSpinBox_GrindX.setObjectName(_fromUtf8("doubleSpinBox_GrindX"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_GrindX, 2, 1, 1, 1)
		self.doubleSpinBox_GrindY = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_GrindY.setDecimals(3)
		self.doubleSpinBox_GrindY.setMinimum(-200.0)
		self.doubleSpinBox_GrindY.setMaximum(200.0)
		self.doubleSpinBox_GrindY.setSingleStep(0.001)
		self.doubleSpinBox_GrindY.setObjectName(_fromUtf8("doubleSpinBox_GrindY"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_GrindY, 2, 2, 1, 1)
		self.doubleSpinBox_GrindZ = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_GrindZ.setDecimals(3)
		self.doubleSpinBox_GrindZ.setMinimum(-50.0)
		self.doubleSpinBox_GrindZ.setMaximum(4.0)
		self.doubleSpinBox_GrindZ.setSingleStep(0.001)
		self.doubleSpinBox_GrindZ.setObjectName(_fromUtf8("doubleSpinBox_GrindZ"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_GrindZ, 2, 3, 1, 1)
		self.doubleSpinBox_GrindSpeed = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_GrindSpeed.setDecimals(3)
		self.doubleSpinBox_GrindSpeed.setMinimum(-200.0)
		self.doubleSpinBox_GrindSpeed.setMaximum(200.0)
		self.doubleSpinBox_GrindSpeed.setSingleStep(0.001)
		self.doubleSpinBox_GrindSpeed.setObjectName(_fromUtf8("doubleSpinBox_GrindSpeed"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_GrindSpeed, 2, 4, 1, 1)
		self.pushButton_CaptureGrind = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_CaptureGrind.sizePolicy().hasHeightForWidth())
		self.pushButton_CaptureGrind.setSizePolicy(sizePolicy)
		self.pushButton_CaptureGrind.setObjectName(_fromUtf8("pushButton_CaptureGrind"))
		self.gridLayout_6.addWidget(self.pushButton_CaptureGrind, 2, 5, 1, 1)
		self.pushButton_GoGrind = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_GoGrind.sizePolicy().hasHeightForWidth())
		self.pushButton_GoGrind.setSizePolicy(sizePolicy)
		self.pushButton_GoGrind.setObjectName(_fromUtf8("pushButton_GoGrind"))
		self.gridLayout_6.addWidget(self.pushButton_GoGrind, 2, 6, 1, 1)
		self.label_21 = QtGui.QLabel(self.tab_6)
		self.label_21.setObjectName(_fromUtf8("label_21"))
		self.gridLayout_6.addWidget(self.label_21, 3, 0, 1, 1)
		self.doubleSpinBox_PolierX = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_PolierX.setDecimals(3)
		self.doubleSpinBox_PolierX.setMinimum(-200.0)
		self.doubleSpinBox_PolierX.setMaximum(200.0)
		self.doubleSpinBox_PolierX.setSingleStep(0.001)
		self.doubleSpinBox_PolierX.setObjectName(_fromUtf8("doubleSpinBox_PolierX"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_PolierX, 3, 1, 1, 1)
		self.doubleSpinBox_PolierY = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_PolierY.setDecimals(3)
		self.doubleSpinBox_PolierY.setMinimum(-200.0)
		self.doubleSpinBox_PolierY.setMaximum(200.0)
		self.doubleSpinBox_PolierY.setSingleStep(0.001)
		self.doubleSpinBox_PolierY.setObjectName(_fromUtf8("doubleSpinBox_PolierY"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_PolierY, 3, 2, 1, 1)
		self.doubleSpinBox_PolierZ = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_PolierZ.setDecimals(3)
		self.doubleSpinBox_PolierZ.setMinimum(-50.0)
		self.doubleSpinBox_PolierZ.setMaximum(4.0)
		self.doubleSpinBox_PolierZ.setSingleStep(0.001)
		self.doubleSpinBox_PolierZ.setObjectName(_fromUtf8("doubleSpinBox_PolierZ"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_PolierZ, 3, 3, 1, 1)
		self.doubleSpinBox_PolierSpeed = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_PolierSpeed.setDecimals(3)
		self.doubleSpinBox_PolierSpeed.setMinimum(-200.0)
		self.doubleSpinBox_PolierSpeed.setMaximum(200.0)
		self.doubleSpinBox_PolierSpeed.setSingleStep(0.001)
		self.doubleSpinBox_PolierSpeed.setObjectName(_fromUtf8("doubleSpinBox_PolierSpeed"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_PolierSpeed, 3, 4, 1, 1)
		self.pushButton_CapturePolier = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_CapturePolier.sizePolicy().hasHeightForWidth())
		self.pushButton_CapturePolier.setSizePolicy(sizePolicy)
		self.pushButton_CapturePolier.setObjectName(_fromUtf8("pushButton_CapturePolier"))
		self.gridLayout_6.addWidget(self.pushButton_CapturePolier, 3, 5, 1, 1)
		self.pushButton_GoPolier = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_GoPolier.sizePolicy().hasHeightForWidth())
		self.pushButton_GoPolier.setSizePolicy(sizePolicy)
		self.pushButton_GoPolier.setObjectName(_fromUtf8("pushButton_GoPolier"))
		self.gridLayout_6.addWidget(self.pushButton_GoPolier, 3, 6, 1, 1)
		self.label_20 = QtGui.QLabel(self.tab_6)
		self.label_20.setObjectName(_fromUtf8("label_20"))
		self.gridLayout_6.addWidget(self.label_20, 4, 0, 1, 1)
		self.doubleSpinBox_DryX = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_DryX.setDecimals(3)
		self.doubleSpinBox_DryX.setMinimum(-200.0)
		self.doubleSpinBox_DryX.setMaximum(200.0)
		self.doubleSpinBox_DryX.setSingleStep(0.001)
		self.doubleSpinBox_DryX.setObjectName(_fromUtf8("doubleSpinBox_DryX"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_DryX, 4, 1, 1, 1)
		self.doubleSpinBox_DryY = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_DryY.setDecimals(3)
		self.doubleSpinBox_DryY.setMinimum(-200.0)
		self.doubleSpinBox_DryY.setMaximum(200.0)
		self.doubleSpinBox_DryY.setSingleStep(0.001)
		self.doubleSpinBox_DryY.setObjectName(_fromUtf8("doubleSpinBox_DryY"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_DryY, 4, 2, 1, 1)
		self.doubleSpinBox_DryZ = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_DryZ.setDecimals(3)
		self.doubleSpinBox_DryZ.setMinimum(-50.0)
		self.doubleSpinBox_DryZ.setMaximum(4.0)
		self.doubleSpinBox_DryZ.setSingleStep(0.001)
		self.doubleSpinBox_DryZ.setObjectName(_fromUtf8("doubleSpinBox_DryZ"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_DryZ, 4, 3, 1, 1)
		self.doubleSpinBox_DrySpeed = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_DrySpeed.setDecimals(3)
		self.doubleSpinBox_DrySpeed.setMinimum(-200.0)
		self.doubleSpinBox_DrySpeed.setMaximum(200.0)
		self.doubleSpinBox_DrySpeed.setSingleStep(0.001)
		self.doubleSpinBox_DrySpeed.setObjectName(_fromUtf8("doubleSpinBox_DrySpeed"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_DrySpeed, 4, 4, 1, 1)
		self.pushButton_CaptureDry = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_CaptureDry.sizePolicy().hasHeightForWidth())
		self.pushButton_CaptureDry.setSizePolicy(sizePolicy)
		self.pushButton_CaptureDry.setObjectName(_fromUtf8("pushButton_CaptureDry"))
		self.gridLayout_6.addWidget(self.pushButton_CaptureDry, 4, 5, 1, 1)
		self.pushButton_GoDry = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_GoDry.sizePolicy().hasHeightForWidth())
		self.pushButton_GoDry.setSizePolicy(sizePolicy)
		self.pushButton_GoDry.setObjectName(_fromUtf8("pushButton_GoDry"))
		self.gridLayout_6.addWidget(self.pushButton_GoDry, 4, 6, 1, 1)
		self.label_19 = QtGui.QLabel(self.tab_6)
		self.label_19.setObjectName(_fromUtf8("label_19"))
		self.gridLayout_6.addWidget(self.label_19, 5, 0, 1, 1)
		self.doubleSpinBox_CameraX = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_CameraX.setDecimals(3)
		self.doubleSpinBox_CameraX.setMinimum(-200.0)
		self.doubleSpinBox_CameraX.setMaximum(200.0)
		self.doubleSpinBox_CameraX.setSingleStep(0.001)
		self.doubleSpinBox_CameraX.setObjectName(_fromUtf8("doubleSpinBox_CameraX"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_CameraX, 5, 1, 1, 1)
		self.doubleSpinBox_CameraY = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_CameraY.setDecimals(3)
		self.doubleSpinBox_CameraY.setMinimum(-200.0)
		self.doubleSpinBox_CameraY.setMaximum(200.0)
		self.doubleSpinBox_CameraY.setSingleStep(0.001)
		self.doubleSpinBox_CameraY.setObjectName(_fromUtf8("doubleSpinBox_CameraY"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_CameraY, 5, 2, 1, 1)
		self.doubleSpinBox_CameraZ = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_CameraZ.setDecimals(3)
		self.doubleSpinBox_CameraZ.setMinimum(-50.0)
		self.doubleSpinBox_CameraZ.setMaximum(4.0)
		self.doubleSpinBox_CameraZ.setSingleStep(0.001)
		self.doubleSpinBox_CameraZ.setObjectName(_fromUtf8("doubleSpinBox_CameraZ"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_CameraZ, 5, 3, 1, 1)
		self.doubleSpinBox_CameraSpeed = QtGui.QDoubleSpinBox(self.tab_6)
		self.doubleSpinBox_CameraSpeed.setDecimals(3)
		self.doubleSpinBox_CameraSpeed.setMinimum(-200.0)
		self.doubleSpinBox_CameraSpeed.setMaximum(200.0)
		self.doubleSpinBox_CameraSpeed.setSingleStep(0.001)
		self.doubleSpinBox_CameraSpeed.setObjectName(_fromUtf8("doubleSpinBox_CameraSpeed"))
		self.gridLayout_6.addWidget(self.doubleSpinBox_CameraSpeed, 5, 4, 1, 1)
		self.pushButton_CaptureCamera = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_CaptureCamera.sizePolicy().hasHeightForWidth())
		self.pushButton_CaptureCamera.setSizePolicy(sizePolicy)
		self.pushButton_CaptureCamera.setObjectName(_fromUtf8("pushButton_CaptureCamera"))
		self.gridLayout_6.addWidget(self.pushButton_CaptureCamera, 5, 5, 1, 1)
		self.pushButton_GoCamera = QtGui.QPushButton(self.tab_6)
		sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.pushButton_GoCamera.sizePolicy().hasHeightForWidth())
		self.pushButton_GoCamera.setSizePolicy(sizePolicy)
		self.pushButton_GoCamera.setObjectName(_fromUtf8("pushButton_GoCamera"))
		self.gridLayout_6.addWidget(self.pushButton_GoCamera, 5, 6, 1, 1)
		self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
		self.tab_4 = QtGui.QWidget()
		self.tab_4.setObjectName(_fromUtf8("tab_4"))
		self.pushButton = QtGui.QPushButton(self.tab_4)
		self.pushButton.setGeometry(QtCore.QRect(30, 30, 151, 41))
		self.pushButton.setObjectName(_fromUtf8("pushButton"))
		self.pushButton_2 = QtGui.QPushButton(self.tab_4)
		self.pushButton_2.setGeometry(QtCore.QRect(30, 90, 151, 41))
		self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
		self.pushButton_3 = QtGui.QPushButton(self.tab_4)
		self.pushButton_3.setGeometry(QtCore.QRect(30, 150, 151, 41))
		self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
		self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.tab_4)
		self.doubleSpinBox_3.setGeometry(QtCore.QRect(200, 50, 81, 31))
		self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
		self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.tab_4)
		self.doubleSpinBox_4.setGeometry(QtCore.QRect(300, 50, 91, 31))
		self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
		self.label_23 = QtGui.QLabel(self.tab_4)
		self.label_23.setGeometry(QtCore.QRect(200, 30, 59, 16))
		self.label_23.setObjectName(_fromUtf8("label_23"))
		self.label_24 = QtGui.QLabel(self.tab_4)
		self.label_24.setGeometry(QtCore.QRect(300, 30, 59, 16))
		self.label_24.setObjectName(_fromUtf8("label_24"))
		self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
		self.gridLayout_2.addWidget(self.tabWidget, 1, 0, 1, 1)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 22))
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName(_fromUtf8("menuFile"))
		self.menuHelp = QtGui.QMenu(self.menubar)
		self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		MainWindow.setStatusBar(self.statusbar)
		self.actionExit = QtGui.QAction(MainWindow)
		self.actionExit.setObjectName(_fromUtf8("actionExit"))
		self.actionAbout = QtGui.QAction(MainWindow)
		self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
		self.actionHelp = QtGui.QAction(MainWindow)
		self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
		self.actionSave_Presets = QtGui.QAction(MainWindow)
		self.actionSave_Presets.setObjectName(_fromUtf8("actionSave_Presets"))
		self.actionLoad_Presets = QtGui.QAction(MainWindow)
		self.actionLoad_Presets.setObjectName(_fromUtf8("actionLoad_Presets"))
		self.menuFile.addAction(self.actionExit)
		self.menuFile.addAction(self.actionSave_Presets)
		self.menuFile.addAction(self.actionLoad_Presets)
		self.menuHelp.addAction(self.actionAbout)
		self.menuHelp.addAction(self.actionHelp)
		self.menubar.addAction(self.menuFile.menuAction())
		self.menubar.addAction(self.menuHelp.menuAction())

		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
		QtCore.QObject.connect(self.Cset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxC.setValue)
		QtCore.QObject.connect(self.spinBoxC, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Cset.setValue)
		QtCore.QObject.connect(self.spinBoxZ, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Zset.setValue)
		QtCore.QObject.connect(self.Zset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxZ.setValue)
		QtCore.QObject.connect(self.spinBoxY, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Yset.setValue)
		QtCore.QObject.connect(self.Yset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxY.setValue)
		QtCore.QObject.connect(self.spinBoxX, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.X1set.setValue)
		QtCore.QObject.connect(self.X1set, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxX.setValue)
		QtCore.QObject.connect(self.spinBoxX2, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.X2set.setValue)
		QtCore.QObject.connect(self.X2set, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxX2.setValue)
		QtCore.QObject.connect(self.spinBoxVmax, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Vmaxset.setValue)
		QtCore.QObject.connect(self.Vmaxset, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.spinBoxVmax.setValue)
		QtCore.QObject.connect(self.pushButtonNotStop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonMotorXAus.setChecked)
		QtCore.QObject.connect(self.pushButtonNotStop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonMotorX2Aus.setChecked)
		QtCore.QObject.connect(self.pushButtonNotStop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonMotorYAus.setChecked)
		QtCore.QObject.connect(self.pushButtonNotStop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonMotorZAus.setChecked)
		QtCore.QObject.connect(self.pushButtonNotStop, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButtonMotorCAus.setChecked)
		QtCore.QObject.connect(self.pushButtonHomeAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButtonHomeX.click)
		QtCore.QObject.connect(self.pushButtonHomeAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButtonHomeX2.click)
		QtCore.QObject.connect(self.pushButtonHomeAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButtonHomeY.click)
		QtCore.QObject.connect(self.pushButtonHomeAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButtonHomeZ.click)
		QtCore.QObject.connect(self.pushButtonHomeAll, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pushButtonHomeC.click)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		MainWindow.setTabOrder(self.tabWidget, self.pushButtonInitX)
		MainWindow.setTabOrder(self.pushButtonInitX, self.pushButtonInitY)
		MainWindow.setTabOrder(self.pushButtonInitY, self.pushButtonInitZ)
		MainWindow.setTabOrder(self.pushButtonInitZ, self.pushButtonHomeX)
		MainWindow.setTabOrder(self.pushButtonHomeX, self.pushButtonHomeY)
		MainWindow.setTabOrder(self.pushButtonHomeY, self.pushButtonHomeZ)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(_translate("MainWindow", "Openpnp CAN Middleware", None))
		self.label_2.setText(_translate("MainWindow", "X2", None))
		self.label_3.setText(_translate("MainWindow", "Y", None))
		self.label_4.setText(_translate("MainWindow", "Z", None))
		self.label_5.setText(_translate("MainWindow", "C", None))
		self.pushButtonNotStop.setText(_translate("MainWindow", "Not Stop", None))
		self.label_6.setText(_translate("MainWindow", "X", None))
		self.pushButtonReadPos.setText(_translate("MainWindow", "Read Positions", None))
		self.pushButtonHomeAll.setText(_translate("MainWindow", "Home All", None))
		self.pushButtonInitX.setText(_translate("MainWindow", "Init X Regler", None))
		self.pushButtonInitX2.setText(_translate("MainWindow", "Init X2 Regler", None))
		self.pushButtonInitY.setText(_translate("MainWindow", "Init Y Regler", None))
		self.pushButtonInitZ.setText(_translate("MainWindow", "Init Z Regler", None))
		self.pushButtonInitC.setText(_translate("MainWindow", "Init C Regler", None))
		self.pushButtonGoX0Y0.setText(_translate("MainWindow", "Go X0 Y0", None))
		self.pushButtonGoZmax.setText(_translate("MainWindow", "Go Z 100000", None))
		self.pushButtonHomeX.setText(_translate("MainWindow", "Home X", None))
		self.pushButtonHomeX2.setText(_translate("MainWindow", "Home X2", None))
		self.pushButtonHomeY.setText(_translate("MainWindow", "Home Y", None))
		self.pushButtonHomeZ.setText(_translate("MainWindow", "Home Z", None))
		self.pushButtonHomeC.setText(_translate("MainWindow", "Home C", None))
		self.pushButtonGoX20.setText(_translate("MainWindow", "Go X2 7500", None))
		self.pushButtonGoC0.setText(_translate("MainWindow", "Go C 0 ", None))
		self.pushButtonMotorXAus.setText(_translate("MainWindow", "Motor X an", None))
		self.pushButtonMotorX2Aus.setText(_translate("MainWindow", "Motor X2 an", None))
		self.pushButtonMotorYAus.setText(_translate("MainWindow", "Motor Y an", None))
		self.pushButtonMotorZAus.setText(_translate("MainWindow", "Motor Z an", None))
		self.pushButtonMotorCAus.setText(_translate("MainWindow", "Motor C an", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Homing", None))
		self.label_12.setText(_translate("MainWindow", "Vmax", None))
		self.label_7.setText(_translate("MainWindow", "X1", None))
		self.label_10.setText(_translate("MainWindow", "Y", None))
		self.pushButtonGo.setText(_translate("MainWindow", "Go", None))
		self.label_8.setText(_translate("MainWindow", "X2", None))
		self.label_9.setText(_translate("MainWindow", "C", None))
		self.label_11.setText(_translate("MainWindow", "Z", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Pos Testing", None))
		self.pushButtonToolTipVac.setText(_translate("MainWindow", "Tool\n"
"Tip\n"
"Vac", None))
		self.label.setText(_translate("MainWindow", "Touchdown", None))
		self.pushButtonUplight.setText(_translate("MainWindow", "Up\n"
"Light", None))
		self.pushButtonToolTipVacRead.setText(_translate("MainWindow", "Tool\n"
"Tip\n"
"Vac\n"
"Read", None))
		self.pushButtonDownlight.setText(_translate("MainWindow", "Down\n"
"Light", None))
		self.pushButtonToolChangerVac.setText(_translate("MainWindow", "Tool\n"
"Changer\n"
" Vac", None))
		self.pushButtonPump.setText(_translate("MainWindow", "Pump", None))
		self.label_13.setText(_translate("MainWindow", "Tip Vac Pressure", None))
		self.pushButtonTouchDownRead.setText(_translate("MainWindow", "Touch\n"
"Down\n"
"Read", None))
		self.progressBarToolTipVacRead.setFormat(_translate("MainWindow", "%v mBar", None))
		self.progressBarTouchDownRead.setFormat(_translate("MainWindow", "%p%", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Actuators, Sensors", None))
		self.pushButton_ZM.setText(_translate("MainWindow", "ZM", None))
		self.pushButton_XM_2.setText(_translate("MainWindow", "XP", None))
		self.pushButton_YM.setText(_translate("MainWindow", "YM", None))
		self.pushButton_YP.setText(_translate("MainWindow", "YP", None))
		self.pushButton_XM.setText(_translate("MainWindow", "XM", None))
		self.pushButton_ZP.setText(_translate("MainWindow", "ZP", None))
		self.pushButtonJoysticMode.setText(_translate("MainWindow", "Joystic mode", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Joystic", None))
		self.label_14.setText(_translate("MainWindow", "X", None))
		self.label_15.setText(_translate("MainWindow", "Y", None))
		self.label_16.setText(_translate("MainWindow", "Z", None))
		self.label_22.setText(_translate("MainWindow", "Speed", None))
		self.label_17.setText(_translate("MainWindow", "Park", None))
		self.pushButton_CapturePark.setText(_translate("MainWindow", "Capture", None))
		self.pushButton_GoPark.setText(_translate("MainWindow", "Go", None))
		self.label_18.setText(_translate("MainWindow", "Grind", None))
		self.pushButton_CaptureGrind.setText(_translate("MainWindow", "Capture", None))
		self.pushButton_GoGrind.setText(_translate("MainWindow", "Go", None))
		self.label_21.setText(_translate("MainWindow", "Polier", None))
		self.pushButton_CapturePolier.setText(_translate("MainWindow", "Capture", None))
		self.pushButton_GoPolier.setText(_translate("MainWindow", "Go", None))
		self.label_20.setText(_translate("MainWindow", "Dry", None))
		self.pushButton_CaptureDry.setText(_translate("MainWindow", "Capture", None))
		self.pushButton_GoDry.setText(_translate("MainWindow", "Go", None))
		self.label_19.setText(_translate("MainWindow", "Camera", None))
		self.pushButton_CaptureCamera.setText(_translate("MainWindow", "Capture", None))
		self.pushButton_GoCamera.setText(_translate("MainWindow", "Go", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "Positionen", None))
		self.pushButton.setText(_translate("MainWindow", "Schleifen mit \n"
"Z hub fahren", None))
		self.pushButton_2.setText(_translate("MainWindow", "Tupfen", None))
		self.pushButton_3.setText(_translate("MainWindow", "Foto machen", None))
		self.label_23.setText(_translate("MainWindow", "Delta", None))
		self.label_24.setText(_translate("MainWindow", "Speed", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Bewegungsprogramme", None))
		self.menuFile.setTitle(_translate("MainWindow", "File", None))
		self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
		self.actionExit.setText(_translate("MainWindow", "Exit", None))
		self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
		self.actionAbout.setText(_translate("MainWindow", "About", None))
		self.actionHelp.setText(_translate("MainWindow", "Help", None))
		self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
		self.actionSave_Presets.setText(_translate("MainWindow", "Save presets", None))
		self.actionLoad_Presets.setText(_translate("MainWindow", "Load Presets", None))


if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	MainWindow = QtGui.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())

